apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnet-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet-manager
  template:
    metadata:
      labels:
        app: testnet-manager
    spec:
      containers:
      - name: testnet-manager
        image: paritytech/testnet-manager:latest
        ports:
        - containerPort: 5000
        args:
          # - uvicorn
          # - main:appz
          # - --host
          # - 0.0.0.0
          # - --port
          # - "5000"
          # - --timeout-keep-alive
          # - "3600"
          # - --workers
          # - "4"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "128Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: testnet-manager-service
spec:
  selector:
    app: testnet-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testnet-manager-ingress
  annotations: {}
spec:
  rules:
  - host: testnetmanager.opticonomy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testnet-manager-service
            port:
              number: 80
  tls: []
